baseurl = "http://MindviewLLC.com"
languageCode = "en-us"
title = "MindView Exceptional Learning Experiences"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	# author = "Bruce Eckel"
	description = "MindView LLC: Exceptional Learning Experiences."

	logo = "/images/mindview-circle.png"
	favicon = "images/favicon.ico"
	banner_image = "/images/MindviewBanner.png"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "green"
    	accent  = "red"
    	header_color = "#6C952C"
    	footer_color = "#6C952C"
    	h1_ruler_color= "green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	#twitter = ""
	#github  = "SoftwareArchitectureForum/SoftwareArchitectureForum-hugo"
	email   = "mindviewinc@gmail.com"

[[menu.main]]
  name   = "MindView"
  url    = "mindview/"
  weight = 10

[[menu.main]]
  name   = "Quick Links"
  url    = "quicklinks/"
  weight = 20

[[menu.main]]
  name   = "Events"
  url    = "events/"
  weight = 30

[[menu.main]]
	name   = "Speaking"
	url    = "speaking/"
	weight = 40

[[menu.main]]
	name   = "About"
	url    = "about/"
	weight = 200


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
